defaults:
  - _self_

hydra:
  job:
    chdir: false

seed: 42
verbose: false
experiment_name: "handwriting_analysis"
device: "cuda"

data:
  data_dir: "C:\\Users\\Emanuele\\Documents\\ProgettiPython\\DL_approach_handwriting\\data\\raw"
  window_size: 10
  stride: 25
  batch_size: 32
  num_workers: 4
  val_split: 0.2
  test_split: 0.1
  num_tasks: 34  
  file_pattern: "T{:02d}.csv"  
  scaler: "robust"
  columns:
    id: "Id"
    label: "Label"
    segment: "Segment"
    task: "Task_ID"

training:
  max_epochs: 10
  learning_rate: 0.00001
  weight_decay: 0.0001
  early_stopping_patience: 10
  gradient_clip_val: 1.0
  checkpoint_dir: "checkpoints"

model:
  hidden_size: 256  # Increased from 128
  num_layers: 3     # Increased from 2
  dropout: 0.2      # Increased from 0.1
  bidirectional: true
  input_dropout: 0.1
  layer_norm_eps: 1e-5
  batch_norm_momentum: 0.1
  bias_init: 1.0    # Forget gate bias initialization