defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  job:
    chdir: false

seed: 42
verbose: false
num_folds: 5
test_mode: true
experiment_name: "handwriting_analysis"
device: "cuda"

data:
  enable_augmentation: false  # Set to false to disable augmentation
  data_dir: "C:/Users/Emanuele/Documents/ProgettiPython/DL_approach_handwriting/data/raw"
  yaml_split_filename: "split_config.yaml"
  config_path: "conf"
  s3_folder_input: "raw-data"
  data_filename: "aggregated_data.csv"
  s3_folder_output: "results"
  output_filename: "results"
  window_sizes: [50]  
  strides: [20] 
  batch_size: 64
  num_workers: 4
  val_size: 0.2
  test_size: 0.1
  num_tasks: 34  
  file_pattern: "T{:02d}.csv"  
  scaler: "robust"
  columns:
    id: "Id"
    label: "Label"
    segment: "Segment"
    task: "Task_ID"

training:
  max_epochs: 1
  learning_rate: 0.0001
  weight_decay: 0.00005
  early_stopping_patience: 30
  gradient_clip_val: 0.4

model:
  type: "transformer"  # Options: "rnn" or "lstm" or "gru" or "xlstm" or "simpleRNN" or "attention_rnn", "han", "lnn", "hatnet", transformer
  hidden_size: 256 # 128 (per transformer: 256 )
  num_layers: 6 # 2 (per transformer: 6 )
  task_embedding_dim: 32
  dropout: 0.3
  embedding_dropout: 0.1
  zoneout_prob: 0.1
  activity_l1: 0.01
  dropout_tcn: 0.2
  tcn_kernel_size: 3
  bidirectional: true
  rnn_specific:
    nonlinearity: "relu"
  lstm_specific:
    layer_norm: true
    use_attention: true
  gru_specific:
    batch_first: true
    bias: true
  xlstm_specific:
    recurrent_dropout: 0.2
  attention_specific:
    n_heads: 8
  han_specific:
    attention_dim: 64
    num_heads: 8  # For multi-head attention if needed
    use_layer_norm: true
    feature_dropout: 0.2
    attention_dropout: 0.1
  lnn_specific:
    num_cells: 4
    dt: 0.05
    complexity_lambda: 0.01
  transformer_specific:
    num_heads: 8
    max_seq_length: 100
    pretrained_model_name: "distilbert-base-uncased"
    freeze_base: false
  
gpu_settings:
  gpu_id: 0  # Specify which GPU to use
  precision: 32  

version_base: "1.1"