# defaults:
#   - _self_

# hydra:
#   job:
#     chdir: false

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  job:
    chdir: false

seed: 42
verbose: false
num_folds: 5
test_mode: true
experiment_name: "handwriting_analysis"
device: "cuda"

data:
  data_dir: "C:\\Users\\Emanuele\\Documents\\ProgettiPython\\DL_approach_handwriting\\data\\raw"
  s3_folder_input: "raw-data"
  data_filename: "aggregated_data.csv"
  s3_folder_output: "results"
  output_filename: "results"
  window_sizes: [25]  
  strides: [10] 
  batch_size: 64
  num_workers: 4
  val_size: 0.2
  test_size: 0.1
  num_tasks: 34  
  file_pattern: "T{:02d}.csv"  
  scaler: "robust"
  columns:
    id: "Id"
    label: "Label"
    segment: "Segment"
    task: "Task_ID"

training:
  max_epochs: 2
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 10
  gradient_clip_val: 1
  # checkpoint_dir: "checkpoints"

model:
  type: "rnn"  # Options: "rnn" or "lstm"
  hidden_size: 256 # 128
  num_layers: 2
  dropout: 0.3 #0.2
  bidirectional: true
  lstm_specific:
    layer_norm: true
  rnn_specific:
    nonlinearity: "relu"
  
gpu_settings:
  gpu_id: 0  # Specify which GPU to use
  precision: 32  # Can be 16 for mixed precision if needed

version_base: "1.1"