defaults:
  - _self_

hydra:
  job:
    chdir: false

seed: 42
verbose: false
num_folds: 5
experiment_name: "handwriting_analysis"
device: "cuda"

data:
  data_dir: "C:\\Users\\Emanuele\\Documents\\ProgettiPython\\DL_approach_handwriting\\data\\raw"
  window_size: 25
  stride: 15
  batch_size: 64
  num_workers: 4
  val_split: 0.2
  test_split: 0.1
  num_tasks: 34  
  file_pattern: "T{:02d}.csv"  
  scaler: "robust"
  columns:
    id: "Id"
    label: "Label"
    segment: "Segment"
    task: "Task_ID"

training:
  max_epochs: 50
  learning_rate: 0.00001
  weight_decay: 0.001
  early_stopping_patience: 10
  gradient_clip_val: 1
  checkpoint_dir: "checkpoints"

model:
  type: "lstm"  # Options: "rnn" or "lstm"
  hidden_size: 128
  num_layers: 2
  dropout: 0.1
  bidirectional: true
  lstm_specific:
    hidden_size: 256  
    num_layers: 3    
    dropout: 0.3      
    proj_size: 64     
    layer_norm: true
  rnn_specific:
    hidden_size: 128
    num_layers: 2
    dropout: 0.1
  
gpu_settings:
  gpu_id: 0  # Specify which GPU to use
  precision: 32  # Can be 16 for mixed precision if needed

version_base: "1.1"