defaults:
  - model: model1
  - process: process1

data:
  raw_dir: ${hydra:runtime.cwd}/data/raw
  processed_dir: ${hydra:runtime.cwd}/data/processed
  final_dir: ${hydra:runtime.cwd}/data/final

training:
  num_epochs: 50
  batch_size: 32
  learning_rate: 0.001
  num_folds: 5