process:
  train_ratio: 0.7
  val_ratio: 0.1
  test_ratio: 0.2
  use_columns: 
    - 'StartTime'
    - 'Duration'
    - 'StartVerticalPosition'
    - 'VerticalSize'
    - 'PeakVerticalVelocity'
    - 'PeakVerticalAcceleration'
    - 'StartHorizontalPosition'
    - 'HorizontalSize'
    - 'StraightnessError'
    - 'Slant'
    - 'LoopSurface'
  categorical_columns:
    - 'Sex'
    - 'Work'
    - 'Education'
  label_column: 'Label'